[workspace]
authors = ["Vinicius <vinipg1@hotmail.com>"]
channels = ["conda-forge"]
name = "mogo-api"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.9.*"
gdal = "3.9.*"
psycopg2 = "*"
pydantic = ">=2.11.7,<3"
requests = "*"
django = "*"
djangorestframework = "*"
python-dotenv = "*"
pillow = "*"
email-validator = "*"

[pypi-dependencies]
# Django & API
djangorestframework-simplejwt = "*"

# Deep Learning (YOLO)
ultralytics = "*"
torch = "*"
torchvision = "*"
dill = "*"

# OCR (PaddleOCR)
paddlepaddle = "*"
paddleocr = "*"

# Dependências extras
setuptools = "*"
numpy = "*"
opencv-python = "*"
shapely = "*"
scipy = "*"

# Celery & Redis
celery = "*"
redis = "*"

# Pode remover essa linha se não usar diretamente
yolo = "*"