# Generated by Django 4.2.24 on 2025-10-06 17:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_deficiencia', models.CharField(choices=[('fisica', 'Física'), ('visual', 'Visual'), ('auditiva', 'Auditiva'), ('intelectual', 'Intelectual'), ('multipla', 'Múltipla')], max_length=20)),
                ('forma_locomocao', models.CharField(choices=[('andar', 'Andar'), ('cadeira_rodas', 'Cadeira de Rodas'), ('muletas', 'Muletas'), ('andador', 'Andador'), ('outro', 'Outro')], default='andar', max_length=50)),
                ('recursos_acessibilidade', models.JSONField(default=list)),
                ('detalhes', models.TextField(blank=True, default='', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Pessoa com Deficiência',
                'verbose_name_plural': 'Pessoas com Deficiência',
                'db_table': 'pcds',
                'ordering': ['tipo_deficiencia'],
            },
        ),
        migrations.CreateModel(
            name='Terceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacao', models.CharField(choices=[('familiar', 'Familiar'), ('cuidador', 'Cuidador Profissional'), ('amigo', 'Amigo'), ('voluntario', 'Voluntário'), ('outro', 'Outro')], max_length=20)),
                ('pcd_assistida_tipo_deficiencia', models.CharField(choices=[('fisica', 'Física'), ('visual', 'Visual'), ('auditiva', 'Auditiva'), ('intelectual', 'Intelectual'), ('multipla', 'Múltipla')], max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Terceiro Responsável',
                'verbose_name_plural': 'Terceiros Responsáveis',
                'db_table': 'terceiros',
                'ordering': ['relacao'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuarios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='usuarios_email_0ff7b3_idx'), models.Index(fields=['nome'], name='usuarios_nome_efb606_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(check=models.Q(('deleted_at__isnull', True), ('deleted_at__gte', models.F('created_at')), _connector='OR'), name='valid_deletion_date'),
        ),
        migrations.AddField(
            model_name='terceiro',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terceiro', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='pcd',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pcd', to='usuarios.usuario'),
        ),
    ]
