# Generated by Django 4.2.24 on 2025-10-06 17:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('tipo_local', models.CharField(choices=[('saude', 'Saúde'), ('educacao', 'Educação'), ('transporte', 'Transporte'), ('comercio', 'Comércio'), ('lazer', 'Lazer'), ('servicos', 'Serviços'), ('religioso', 'Local Religioso'), ('cultural', 'Cultural'), ('outro', 'Outro')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
                'db_table': 'locais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origem_lat', models.FloatField()),
                ('origem_lng', models.FloatField()),
                ('destino_lat', models.FloatField()),
                ('destino_lng', models.FloatField()),
                ('polyline_line', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('score_acessibilidade', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'db_table': 'rotas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoBusca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origem_texto', models.CharField(max_length=300)),
                ('destino_texto', models.CharField(max_length=300)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('origem_lat', models.FloatField(blank=True, default=None, null=True)),
                ('origem_lng', models.FloatField(blank=True, default=None, null=True)),
                ('destino_lat', models.FloatField(blank=True, default=None, null=True)),
                ('destino_lng', models.FloatField(blank=True, default=None, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_buscas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Histórico de Busca',
                'verbose_name_plural': 'Históricos de Busca',
                'db_table': 'historico_buscas',
                'ordering': ['-data_hora'],
            },
        ),
    ]
