# Generated by Django 4.2.23 on 2025-11-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='erro_mensagem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='status_processamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20),
        ),
    ]
