"""
Django settings for mogo project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# ========== CONFIGURAÇÃO GDAL/GEOS PARA WINDOWS ==========
if os.name == 'nt':  # Windows
    # Caminho exato do seu ambiente pixi (baseado no pixi info)
    pixi_prefix = Path(os.environ.get('PIXI_PREFIX'))

    # Caminhos das bibliotecas
    library_bin = pixi_prefix / 'Library' / 'bin'
    library_share = pixi_prefix / 'Library' / 'share'

    if library_bin.exists():
        # Adicionar ao PATH do sistema
        os.environ['PATH'] = str(library_bin) + ';' + \
            os.environ.get('PATH', '')

        # Configurações específicas do GDAL
        os.environ['GDAL_DATA'] = str(library_share / 'gdal')
        os.environ['PROJ_LIB'] = str(library_share / 'proj')

        # Para GDAL 3.9.0, definir biblioteca específica
        gdal_dll = library_bin / 'gdal.dll'  # Para GDAL 3.9.0
        if gdal_dll.exists():
            GDAL_LIBRARY_PATH = str(gdal_dll)

        geos_dll = library_bin / 'geos_c.dll'
        if geos_dll.exists():
            GEOS_LIBRARY_PATH = str(geos_dll)

        print(f"✅ GDAL 3.9.0 configurado: {library_bin}")
    else:
        print(f"⚠️ Pasta não encontrada: {library_bin}")
# ========================================================

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w9n=%xip1s(p_a=g-^7^ns$@ynx=%f@w84&7sn*3qu_&4qkb9j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'rest_framework',

    # Apps locais
    'usuarios',
    'navigation',
    'social',
]

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'common.exceptions_handler.custom_exception_handler',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mogo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mogo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get('DATABASE_NAME'),
        'USER': os.environ.get('DATABASE_USER'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD'),
        'HOST': os.environ.get('DATABASE_HOST'),
        'PORT': os.environ.get('DATABASE_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
